import { escapeLatex, escapeLatexUrl, processBodyText, formatSubjectForLatex, formatAddressForLatex } from './escaper';
import type { DocumentData, Reference, Enclosure, Paragraph, CopyTo } from '@/types/document';
import { DOC_TYPE_CONFIG } from '@/types/document';

interface DocumentStore {
  docType: string;
  formData: Partial<DocumentData>;
  references: Reference[];
  enclosures: Enclosure[];
  paragraphs: Paragraph[];
  copyTos: CopyTo[];
}

// const PARAGRAPH_INDENT_SPACES = 4; // Used in getBodyText for plain text output

function getParagraphLabel(level: number, count: number): string {
  const patterns = [
    (n: number) => `${n}.`,
    (n: number) => `${String.fromCharCode(96 + n)}.`,
    (n: number) => `(${n})`,
    (n: number) => `(${String.fromCharCode(96 + n)})`,
  ];
  const pattern = patterns[level % 4];
  return pattern(count);
}

function calculateLabels(paragraphs: Paragraph[]): string[] {
  const labels: string[] = [];
  const counters = [0, 0, 0, 0, 0, 0, 0, 0];

  for (const para of paragraphs) {
    for (let i = para.level + 1; i < 8; i++) {
      counters[i] = 0;
    }
    counters[para.level]++;
    labels.push(getParagraphLabel(para.level, counters[para.level]));
  }

  return labels;
}

// getBodyText is used for plain text output (not LaTeX)
// Keeping for potential future use in exports
// function getBodyText(paragraphs: Paragraph[]): string {
//   const labels = calculateLabels(paragraphs);
//   return paragraphs
//     .map((para, i) => {
//       const indent = ' '.repeat(para.level * PARAGRAPH_INDENT_SPACES);
//       return `${indent}${labels[i]}  ${para.text}`;
//     })
//     .join('\n\n');
// }

export function generateDocumentTex(store: DocumentStore): string {
  const data = store.formData;
  // config will be used for document-type specific variations
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;
  const isMOAMode = config.uiMode === 'moa';
  const isJointLetterMode = config.uiMode === 'joint';

  let tex = `%=============================================================================
% DOCUMENT CONFIGURATION - Generated by dondocs
%=============================================================================

\\setDocumentType{${store.docType}}
\\setFontSize{${data.fontSize || '12pt'}}
\\setFontFamily{${data.fontFamily || 'times'}}
\\setPageNumberStyle{${data.pageNumbering || 'none'}}

`;

  // For MOA/MOU: document-level SSIC/Serial/Date = Senior command values
  // For Joint Letter: no document-level SSIC (handled in signatory.tex)
  // The cached template uses DocumentSSIC etc for Senior side
  const ssic = isMOAMode ? data.seniorSSIC : (isJointLetterMode ? '' : data.ssic);
  const serial = isMOAMode ? data.seniorSerial : (isJointLetterMode ? '' : data.serial);
  const docDate = isMOAMode ? data.seniorDate : (isJointLetterMode ? '' : data.date);

  // For business letters, also set the BusinessDate command
  const isBusinessLetter = store.docType === 'business_letter';

  // For joint letters, use joint-specific fields
  const fromLine = isJointLetterMode ? data.jointSeniorFrom : data.from;
  const toLine = isJointLetterMode ? data.jointTo : data.to;
  // Subject line must be in ALL CAPS per SECNAV M-5216.5
  // Also wrap at 57 characters per SECNAV formatting requirements
  const rawSubject = isJointLetterMode ? data.jointSubject : (isMOAMode ? data.moaSubject : data.subject);
  const subjectLine = formatSubjectForLatex(rawSubject?.toUpperCase());

  tex += `\\setSSIC{${escapeLatex(ssic)}}
\\setSerial{${escapeLatex(serial)}}
\\setDocumentDate{${escapeLatex(docDate)}}
${isBusinessLetter ? `\\setBusinessDate{${escapeLatex(docDate)}}` : '% Not a business letter'}

${data.inReplyTo ? `\\enableInReplyReferTo
\\setInReplyReferTo{${escapeLatex(data.inReplyToText)}}` : '% No In Reply Refer To'}

\\setFrom
    {${formatAddressForLatex(fromLine)}}
    {}{}{}

${isBusinessLetter ? `% Business letter: format recipient address as block with line breaks
% Split by newlines (handle both \\n and \\r\\n), escape each line, join with \\\\
\\setBusinessRecipientAddress{${
  (toLine || '')
    .split(/\r?\n/)
    .filter(line => line.trim())
    .map(line => escapeLatex(line.trim()))
    .join('\\\\\n')
}}` : `\\setTo
    {${formatAddressForLatex(toLine)}}
    {}{}{}{}`}

${data.via?.trim() ? `\\setVia
    {${escapeLatex(data.via?.split('\n')[0] || '')}}
    {${escapeLatex(data.via?.split('\n')[1] || '')}}
    {${escapeLatex(data.via?.split('\n')[2] || '')}}
    {${escapeLatex(data.via?.split('\n')[3] || '')}}` : '% No Via'}

\\setSubject{${subjectLine}}

\\setBusinessSalutation{${escapeLatex((data.salutation || 'Dear Sir or Madam:').trim())}}
\\setBusinessClose{${escapeLatex(data.complimentaryClose || 'Very respectfully,')}}

\\setPOC{${escapeLatex(data.pocEmail)}}
`;

  return tex;
}

export function generateLetterheadTex(store: DocumentStore): string {
  const data = store.formData;

  // Parse address: format is "Street/Box, City State ZIP" (comma-separated)
  // Split on first comma to get street line and city/state/zip line
  const addressParts = (data.unitAddress || '').split(',');
  const addressLine1 = addressParts[0]?.trim() || '';
  const addressLine2 = addressParts.slice(1).join(',').trim() || '';

  // Check if unit line 2 has content
  const hasLine2 = !!data.unitLine2?.trim();

  // When line 2 is empty, shift content up to eliminate the gap
  // Line 2 empty: UnitName, Address1, Address2, (empty)
  // Line 2 has content: UnitName, UnitLine2, Address1, Address2
  const line1 = escapeLatex(data.unitLine1);
  const line2 = hasLine2 ? escapeLatex(data.unitLine2) : escapeLatex(addressLine1);
  const line3 = hasLine2 ? escapeLatex(addressLine1) : escapeLatex(addressLine2);
  const line4 = hasLine2 ? escapeLatex(addressLine2) : '';

  return `%=============================================================================
% LETTERHEAD CONFIGURATION - Generated by dondocs
% Per SECNAV M-5216.5: Unit name, address
%=============================================================================

% Seal type: dow (Department of War) or dod (Department of Defense)
\\setSealType{${data.sealType || 'dow'}}

% Department/Service: usmc, navy, or dod
\\setDepartment{${data.department || 'usmc'}}

% Letterhead color: blue (default) or black
\\setLetterheadColor{${data.letterheadColor || 'blue'}}

\\setLetterhead
    {${line1}}
    {${line2}}
    {${line3}}
    {${line4}}
`;
}

// Capitalize first letter of each word
function capitalizeWord(word: string | undefined): string {
  if (!word) return '';
  return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}

export function generateSignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;

  // Check if this is a dual-signature document (MOA/MOU)
  if (config.uiMode === 'moa') {
    return generateMOASignatoryTex(store);
  }

  // Check if this is a joint letter (dual letterheads and signatures)
  if (config.uiMode === 'joint') {
    return generateJointLetterSignatoryTex(store);
  }

  // Properly capitalize names: First Middle LAST
  const firstName = capitalizeWord(data.sigFirst);
  const middleName = capitalizeWord(data.sigMiddle);
  const lastName = data.sigLast?.toUpperCase() || '';

  const fullName = [firstName, middleName, lastName]
    .filter(Boolean)
    .join(' ');

  // Abbreviated format: F. M. LASTNAME
  const abbrevName = [
    firstName ? `${firstName[0].toUpperCase()}.` : '',
    middleName ? `${middleName[0].toUpperCase()}.` : '',
    lastName,
  ]
    .filter(Boolean)
    .join(' ');

  let byDirectionTex = '';
  if (data.byDirection) {
    const authority = data.byDirectionAuthority || 'the Commanding Officer';
    byDirectionTex = `\\setByDirection{By direction of ${escapeLatex(authority)}}`;
  }

  // Set signature type and image
  // signatureType: 'none' = just typed name, 'image' = uploaded signature, 'digital' = empty field for CAC signing
  const signatureType = data.signatureType || 'none';
  let signatureConfigTex = '';

  if (signatureType === 'image' && data.signatureImage?.data) {
    // Use uploaded signature image
    signatureConfigTex = '\\setSignatureImage{signature.png}';
  } else if (signatureType === 'digital') {
    // Create empty digital signature field
    signatureConfigTex = '\\setDigitalSignatureField';
  } else {
    // No signature image or field
    signatureConfigTex = '\\setSignatureImage{}';
  }

  return `%=============================================================================
% SIGNATURE CONFIGURATION - Generated by dondocs
%=============================================================================

\\setSignatory
    {${escapeLatex(firstName)}}
    {${escapeLatex(middleName)}}
    {${escapeLatex(lastName)}}
    {${escapeLatex(data.sigRank)}}
    {${escapeLatex(data.sigTitle)}}

\\setSignatoryName{${escapeLatex(fullName)}}
\\setSignatoryAbbrev{${escapeLatex(abbrevName)}}

${byDirectionTex}

${signatureConfigTex}
`;
}

// Generate MOA/MOU specific signatory configuration (dual signatures)
// Uses ONLY commands that exist in the original cached template
function generateMOASignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const signatureType = data.signatureType || 'none';

  // Digital signature field for dual signatures
  let signatureConfigTex = '';
  if (signatureType === 'digital') {
    signatureConfigTex = '\\setDigitalSignatureField';
  }

  // Senior signatory name formatting (same as standard signatory)
  const seniorFirstName = capitalizeWord(data.seniorSigName?.split(' ')[0]);
  const seniorLastName = data.seniorSigName?.split(' ').slice(-1)[0]?.toUpperCase() || '';
  const seniorFullName = data.seniorSigName || '';
  const seniorAbbrev = seniorFirstName ? `${seniorFirstName[0]}. ${seniorLastName}` : seniorLastName;

  // Junior signatory name formatting (abbreviated like senior: "R. CHIOFALO")
  const juniorFirstName = capitalizeWord(data.juniorSigName?.split(' ')[0]);
  const juniorLastName = data.juniorSigName?.split(' ').slice(-1)[0]?.toUpperCase() || '';
  const juniorAbbrev = juniorFirstName ? `${juniorFirstName[0]}. ${juniorLastName}` : juniorLastName;

  // Use EXISTING commands only - Senior uses document-level fields + standard signatory
  // Junior uses Junior-prefixed fields (which already exist)
  return `%=============================================================================
% MOA/MOU DUAL SIGNATURE CONFIGURATION - Generated by dondocs
%=============================================================================

% Senior Command (Signs Last - Right Side)
% Uses SeniorCommandName (exists) + document-level SSIC/Serial/Date + standard signatory
\\renewcommand{\\SeniorCommandName}{${escapeLatex(data.seniorCommandName)}}

% Senior signatory uses standard signatory fields
\\setSignatory
    {${escapeLatex(seniorFirstName)}}
    {}
    {${escapeLatex(seniorLastName)}}
    {${escapeLatex(data.seniorSigRank)}}
    {${escapeLatex(data.seniorSigTitle)}}
\\setSignatoryName{${escapeLatex(seniorFullName)}}
\\setSignatoryAbbrev{${escapeLatex(seniorAbbrev)}}

% Junior Command (Signs First - Left Side) - uses Junior-prefixed fields
\\renewcommand{\\JuniorCommandName}{${escapeLatex(data.juniorCommandName)}}
\\renewcommand{\\JuniorSSIC}{${escapeLatex(data.juniorSSIC)}}
\\renewcommand{\\JuniorSerial}{${escapeLatex(data.juniorSerial)}}
\\renewcommand{\\JuniorDate}{${escapeLatex(data.juniorDate)}}
\\renewcommand{\\JuniorSignatoryName}{${escapeLatex(juniorAbbrev)}}
\\renewcommand{\\JuniorSignatoryRank}{${escapeLatex(data.juniorSigRank)}}
\\renewcommand{\\JuniorSignatoryTitle}{${escapeLatex(data.juniorSigTitle)}}

${signatureConfigTex}
`;
}

// Generate Joint Letter specific configuration (dual letterheads and signatures)
// Uses commands from joint_letter.tex template
function generateJointLetterSignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const signatureType = data.signatureType || 'none';

  // Digital signature field for dual signatures
  let signatureConfigTex = '';
  if (signatureType === 'digital') {
    signatureConfigTex = '\\setDigitalSignatureField';
  }

  // Parse senior signatory name (format: "J. A. SMITH" -> "J. A." first, "SMITH" last)
  const seniorFullName = data.jointSeniorSigName || '';
  const seniorParts = seniorFullName.split(' ');
  const seniorLastName = seniorParts[seniorParts.length - 1]?.toUpperCase() || '';
  const seniorFirstInitials = seniorParts.slice(0, -1).join(' ');
  const seniorAbbrev = seniorFullName.toUpperCase();

  // Junior signatory name (used as full uppercase name)
  const juniorFullName = data.jointJuniorSigName || '';

  return `%=============================================================================
% JOINT LETTER DUAL CONFIGURATION - Generated by dondocs
% Per SECNAV M-5216.5 Ch 7, Para 7-1.2; Figure 7-4
%=============================================================================

% Senior Command (Right Side - Signs Last)
\\renewcommand{\\SeniorCommandName}{${escapeLatex(data.jointSeniorName)}}
\\renewcommand{\\SeniorCommandZip}{${escapeLatex(data.jointSeniorZip)}}
\\renewcommand{\\SeniorCommandCode}{${escapeLatex(data.jointSeniorCode)}}
\\renewcommand{\\SeniorFromLine}{${escapeLatex(data.jointSeniorFrom)}}

% Senior signatory uses standard signatory fields
\\setSignatory
    {${escapeLatex(seniorFirstInitials)}}
    {}
    {${escapeLatex(seniorLastName)}}
    {}
    {${escapeLatex(data.jointSeniorSigTitle)}}
\\setSignatoryName{${escapeLatex(seniorFullName)}}
\\setSignatoryAbbrev{${escapeLatex(seniorAbbrev)}}

% Junior Command (Left Side - Signs First)
\\renewcommand{\\JuniorCommandName}{${escapeLatex(data.jointJuniorName)}}
\\renewcommand{\\JuniorCommandZip}{${escapeLatex(data.jointJuniorZip)}}
\\renewcommand{\\JuniorCommandCode}{${escapeLatex(data.jointJuniorCode)}}
\\renewcommand{\\JuniorSSIC}{${escapeLatex(data.jointJuniorSSIC)}}
\\renewcommand{\\JuniorSerial}{${escapeLatex(data.jointJuniorSerial)}}
\\renewcommand{\\JuniorDate}{${escapeLatex(data.jointJuniorDate)}}
\\renewcommand{\\JuniorFromLine}{${escapeLatex(data.jointJuniorFrom)}}
\\renewcommand{\\JuniorSignatoryName}{${escapeLatex(juniorFullName.toUpperCase())}}
\\renewcommand{\\JuniorSignatoryTitle}{${escapeLatex(data.jointJuniorSigTitle)}}

% Common location (appears in letterhead)
\\renewcommand{\\CommonLocation}{${escapeLatex(data.jointCommonLocation)}}

${signatureConfigTex}
`;
}

export function generateFlagsTex(store: DocumentStore): string {
  let flags = '% Flags - Generated by dondocs\n';
  if (store.references.length > 0) {
    flags += '\\setHasReferences\n';
  }
  if (store.enclosures.length > 0) {
    flags += '\\setHasEnclosures\n';
  }
  if (store.formData.includeHyperlinks) {
    flags += '\\setHyperlinksEnabled\n';
  }
  return flags;
}

export function generateReferencesTex(store: DocumentStore): string {
  if (store.references.length === 0) {
    return '% No references\n';
  }

  return `%=============================================================================
% REFERENCES - Generated by dondocs
% Count: ${store.references.length} references
%=============================================================================

${store.references.map((r) => `\\refitem{${r.letter}}{${escapeLatex(r.title)}}`).join('\n')}
`;
}

export function generateReferenceUrlsTex(store: DocumentStore): string {
  const refsWithUrls = store.references.filter((r) => r.url?.trim());
  if (refsWithUrls.length === 0) return '% No reference URLs\n';

  return `%=============================================================================
% REFERENCE URLS - Generated by dondocs
%=============================================================================

${refsWithUrls.map((r) => `\\setRefURL{${r.letter}}{${escapeLatexUrl(r.url)}}`).join('\n')}
`;
}

export function generateEnclosuresTex(store: DocumentStore): string {
  if (store.enclosures.length === 0) {
    return '% No enclosures\n';
  }

  return `%=============================================================================
% ENCLOSURES - Generated by dondocs
% Count: ${store.enclosures.length} enclosures
%=============================================================================

${store.enclosures
    .map((e, i) => {
      // Always use JSPDF marker - JavaScript handles ALL enclosure pages
      // This ensures correct ordering (text-only and PDF enclosures in sequence)
      return `\\enclosure{${i + 1}}{JSPDF}{${escapeLatex(e.title || 'Untitled')}}`;
    })
    .join('\n')}
`;
}

export function generateCopyToTex(store: DocumentStore): string {
  if (store.copyTos.length === 0) {
    return '% No copy-to recipients\n';
  }

  return `%=============================================================================
% COPY TO (DISTRIBUTION) - Generated by dondocs
% Count: ${store.copyTos.length} recipients
%=============================================================================

\\setHasCopyTo
${store.copyTos.map((ct, i) => `\\copytoentry{${i + 1}}{${escapeLatex(ct.text)}}`).join('\n')}
`;
}

// Convert header to Title Case per SECNAV M-5216.5 Ch 7 ¶13d
function toTitleCase(str: string): string {
  // Words that should remain lowercase (unless first word)
  const lowercaseWords = ['a', 'an', 'and', 'as', 'at', 'but', 'by', 'for', 'in', 'nor', 'of', 'on', 'or', 'so', 'the', 'to', 'up', 'yet'];
  
  return str.split(' ').map((word, index) => {
    const lower = word.toLowerCase();
    // Always capitalize first word, otherwise check if it's a lowercase word
    if (index === 0 || !lowercaseWords.includes(lower)) {
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    }
    return lower;
  }).join(' ');
}

export function generateBodyTex(store: DocumentStore): string {
  const labels = calculateLabels(store.paragraphs);
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;

  // Business letters and endorsements don't use numbered paragraphs
  const useNumberedParagraphs = config.compliance.numberedParagraphs;
  // Business letters use 0.5" first-line indent instead of numbers
  const isBusinessLetter = store.docType === 'business_letter';

  let latex = `%=============================================================================
% DOCUMENT BODY - Generated by dondocs
% SECNAV M-5216.5 Ch 7 ¶13: "Do not indent the continuation lines of a subparagraph."
% Continuation lines return to the label position using \\leftskip
%=============================================================================

`;

  for (let i = 0; i < store.paragraphs.length; i++) {
    const para = store.paragraphs[i];
    const label = useNumberedParagraphs ? labels[i] : '';
    const headerText = para.header?.trim();

    if (para.level === 0) {
      // Level 0: Main paragraph with optional underlined header
      // Per SECNAV M-5216.5 Ch 7 ¶13d: "Underline any heading and capitalize its key words"
      if (isBusinessLetter) {
        // Business letter: 0.5" first-line indent, no numbers
        if (headerText) {
          const formattedHeader = toTitleCase(headerText);
          latex += `\\vspace{12pt}\n\\noindent\\hspace{0.5in}\\underline{${escapeLatex(formattedHeader)}}.  ${processBodyText(para.text)}\n\n`;
        } else {
          latex += `\\vspace{12pt}\n\\noindent\\hspace{0.5in}${processBodyText(para.text)}\n\n`;
        }
      } else if (headerText) {
        const formattedHeader = toTitleCase(headerText);
        latex += `\\vspace{12pt}\n\\noindent ${label} \\underline{${escapeLatex(formattedHeader)}}.  ${processBodyText(para.text)}\n\n`;
      } else {
        latex += `\\vspace{12pt}\n\\noindent ${label}  ${processBodyText(para.text)}\n\n`;
      }
    } else {
      // Subparagraphs: Use leftskip for proper continuation line wrapping
      // Per SECNAV Ch 7 ¶13: continuation lines return to label position
      const levelIndent = isBusinessLetter ? (para.level + 1) * 0.5 : para.level * 0.25; // Business: 0.5" per level, Others: 0.25"

      if (headerText) {
        const formattedHeader = toTitleCase(headerText);
        latex += `\\vspace{6pt}\n{\\leftskip=${levelIndent}in\n\\noindent ${label} \\underline{${escapeLatex(formattedHeader)}}. ${processBodyText(para.text)}\\par}\n\n`;
      } else {
        latex += `\\vspace{6pt}\n{\\leftskip=${levelIndent}in\n\\noindent ${label} ${processBodyText(para.text)}\\par}\n\n`;
      }
    }
  }

  return latex;
}

export function generateClassificationTex(store: DocumentStore): string {
  const data = store.formData;

  if (data.classLevel === 'unclassified' || !data.classLevel) {
    return '% Unclassified - no classification markings\n';
  }

  if (data.classLevel === 'cui') {
    return `%=============================================================================
% CUI CONFIGURATION - Generated by dondocs
%=============================================================================

\\setCUI
\\setCUIControlledBy{${escapeLatex(data.cuiControlledBy)}}
\\setCUICategory{${escapeLatex(data.cuiCategory)}}
\\setCUIDissemination{${escapeLatex(data.cuiDissemination)}}
\\setCUIDistStatement{${escapeLatex(data.cuiDistStatement)}}
\\setPOC{${escapeLatex(data.pocEmail)}}
`;
  }

  // Handle custom classification - just output the text verbatim as banner only
  // Uses \setCustomClassification which sets banners but NOT the classified info block
  if (data.classLevel === 'custom' && data.customClassification) {
    return `%=============================================================================
% CUSTOM CLASSIFICATION - Generated by dondocs
%=============================================================================

\\setCustomClassification{${escapeLatex(data.customClassification)}}
`;
  }

  const classLevelMap: Record<string, string> = {
    confidential: 'CONFIDENTIAL',
    secret: 'SECRET',
    top_secret: 'TOP SECRET',
    top_secret_sci: 'TOP SECRET//SCI',
  };

  return `%=============================================================================
% CLASSIFICATION CONFIGURATION - Generated by dondocs
%=============================================================================

\\setClassification{${classLevelMap[data.classLevel] || 'SECRET'}}
\\setClassifiedBy{${escapeLatex(data.classifiedBy)}}
\\setDerivedFrom{${escapeLatex(data.derivedFrom)}}
\\setDeclassifyOn{${escapeLatex(data.declassifyOn)}}
\\setClassificationReason{${escapeLatex(data.classReason)}}
\\setPOC{${escapeLatex(data.classifiedPocEmail)}}
`;
}

export interface EnclosureData {
  number: number;
  title: string;
  data?: ArrayBuffer; // undefined = text-only enclosure (no PDF)
  pageStyle?: 'border' | 'fullpage' | 'fit';
  hasCoverPage?: boolean;
  coverPageDescription?: string;
}

export interface ReferenceUrlData {
  letter: string;
  url: string;
}

export interface GeneratedFiles {
  texFiles: Record<string, string>;
  enclosures: EnclosureData[];
  includeHyperlinks: boolean;
  signatureImage?: Uint8Array; // PNG data for signature image
  referenceUrls: ReferenceUrlData[]; // URLs for reference hyperlinks
}

// Helper to convert base64 to Uint8Array
function base64ToUint8Array(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

export function generateAllLatexFiles(store: DocumentStore): GeneratedFiles {
  // Files are written to root level to match \input{} paths in latex-templates.js
  const texFiles: Record<string, string> = {
    'document.tex': generateDocumentTex(store),
    'letterhead.tex': generateLetterheadTex(store),
    'signatory.tex': generateSignatoryTex(store),
    'flags.tex': generateFlagsTex(store),
    'references.tex': generateReferencesTex(store),
    'reference-urls.tex': generateReferenceUrlsTex(store),
    'encl-config.tex': generateEnclosuresTex(store),
    'copyto-config.tex': generateCopyToTex(store),
    'body.tex': generateBodyTex(store),
    'classification.tex': generateClassificationTex(store),
  };

  // Collect ALL enclosures for JavaScript handling (maintains correct order)
  const enclosures: EnclosureData[] = store.enclosures.map((encl, i) => ({
    number: i + 1,
    title: encl.title || 'Untitled',
    data: encl.file?.data, // undefined if no PDF attached
    pageStyle: encl.pageStyle,
    hasCoverPage: encl.hasCoverPage,
    coverPageDescription: encl.coverPageDescription,
  }));

  // Convert signature image from base64 to Uint8Array if present
  const signatureImage = store.formData.signatureImage?.data
    ? base64ToUint8Array(store.formData.signatureImage.data)
    : undefined;

  // Collect reference URLs for hyperlink creation
  const referenceUrls: ReferenceUrlData[] = store.references
    .filter((r) => r.url?.trim())
    .map((r) => ({ letter: r.letter, url: r.url! }));

  return { texFiles, enclosures, includeHyperlinks: !!store.formData.includeHyperlinks, signatureImage, referenceUrls };
}
