import { escapeLatex, escapeLatexUrl, processBodyText } from './escaper';
import type { DocumentData, Reference, Enclosure, Paragraph, CopyTo } from '@/types/document';
import { DOC_TYPE_CONFIG } from '@/types/document';

interface DocumentStore {
  docType: string;
  formData: Partial<DocumentData>;
  references: Reference[];
  enclosures: Enclosure[];
  paragraphs: Paragraph[];
  copyTos: CopyTo[];
}

// const PARAGRAPH_INDENT_SPACES = 4; // Used in getBodyText for plain text output

function getParagraphLabel(level: number, count: number): string {
  const patterns = [
    (n: number) => `${n}.`,
    (n: number) => `${String.fromCharCode(96 + n)}.`,
    (n: number) => `(${n})`,
    (n: number) => `(${String.fromCharCode(96 + n)})`,
  ];
  const pattern = patterns[level % 4];
  return pattern(count);
}

function calculateLabels(paragraphs: Paragraph[]): string[] {
  const labels: string[] = [];
  const counters = [0, 0, 0, 0, 0, 0, 0, 0];

  for (const para of paragraphs) {
    for (let i = para.level + 1; i < 8; i++) {
      counters[i] = 0;
    }
    counters[para.level]++;
    labels.push(getParagraphLabel(para.level, counters[para.level]));
  }

  return labels;
}

// getBodyText is used for plain text output (not LaTeX)
// Keeping for potential future use in exports
// function getBodyText(paragraphs: Paragraph[]): string {
//   const labels = calculateLabels(paragraphs);
//   return paragraphs
//     .map((para, i) => {
//       const indent = ' '.repeat(para.level * PARAGRAPH_INDENT_SPACES);
//       return `${indent}${labels[i]}  ${para.text}`;
//     })
//     .join('\n\n');
// }

export function generateDocumentTex(store: DocumentStore): string {
  const data = store.formData;
  // config will be used for document-type specific variations
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;
  const isMOAMode = config.uiMode === 'moa';

  let tex = `%=============================================================================
% DOCUMENT CONFIGURATION - Generated by libo-secured
%=============================================================================

\\setDocumentType{${store.docType}}
\\setFontSize{${data.fontSize || '12pt'}}
\\setFontFamily{${data.fontFamily || 'courier'}}
\\setPageNumberStyle{${data.pageNumbering || 'none'}}

`;

  // For MOA/MOU: document-level SSIC/Serial/Date = Senior command values
  // The cached template uses DocumentSSIC etc for Senior side
  const ssic = isMOAMode ? data.seniorSSIC : data.ssic;
  const serial = isMOAMode ? data.seniorSerial : data.serial;
  const docDate = isMOAMode ? data.seniorDate : data.date;

  tex += `\\setSSIC{${escapeLatex(ssic)}}
\\setSerial{${escapeLatex(serial)}}
\\setDocumentDate{${escapeLatex(docDate)}}

${data.inReplyTo ? `\\enableInReplyReferTo
\\setInReplyReferTo{${escapeLatex(data.inReplyToText)}}` : '% No In Reply Refer To'}

\\setFrom
    {${escapeLatex(data.from)}}
    {}{}{}

\\setTo
    {${escapeLatex(data.to)}}
    {}{}{}

${data.via?.trim() ? `\\setVia
    {${escapeLatex(data.via?.split('\n')[0] || '')}}
    {${escapeLatex(data.via?.split('\n')[1] || '')}}
    {${escapeLatex(data.via?.split('\n')[2] || '')}}
    {${escapeLatex(data.via?.split('\n')[3] || '')}}` : '% No Via'}

\\setSubject{${escapeLatex(isMOAMode ? data.moaSubject : data.subject)}}

\\setBusinessSalutation{Dear Sir or Madam:}
\\setBusinessClose{Very respectfully,}

\\setPOC{${escapeLatex(data.pocEmail)}}
`;

  return tex;
}

export function generateLetterheadTex(store: DocumentStore): string {
  const data = store.formData;

  // Parse address: format is "Street/Box, City State ZIP" (comma-separated)
  // Split on first comma to get street line and city/state/zip line
  const addressParts = (data.unitAddress || '').split(',');
  const addressLine1 = addressParts[0]?.trim() || '';
  const addressLine2 = addressParts.slice(1).join(',').trim() || '';

  // Check if unit line 2 has content
  const hasLine2 = !!data.unitLine2?.trim();

  // When line 2 is empty, shift content up to eliminate the gap
  // Line 2 empty: UnitName, Address1, Address2, (empty)
  // Line 2 has content: UnitName, UnitLine2, Address1, Address2
  const line1 = escapeLatex(data.unitLine1);
  const line2 = hasLine2 ? escapeLatex(data.unitLine2) : escapeLatex(addressLine1);
  const line3 = hasLine2 ? escapeLatex(addressLine1) : escapeLatex(addressLine2);
  const line4 = hasLine2 ? escapeLatex(addressLine2) : '';

  return `%=============================================================================
% LETTERHEAD CONFIGURATION - Generated by libo-secured
% Per SECNAV M-5216.5: Unit name, address
%=============================================================================

% Seal type: dod (current) or dow (historical Department of War)
\\setSealType{${data.sealType || 'dod'}}

% Department/Service: usmc, navy, or dod
\\setDepartment{${data.department || 'usmc'}}

\\setLetterhead
    {${line1}}
    {${line2}}
    {${line3}}
    {${line4}}
`;
}

// Capitalize first letter of each word
function capitalizeWord(word: string | undefined): string {
  if (!word) return '';
  return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}

export function generateSignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;

  // Check if this is a dual-signature document (MOA/MOU)
  if (config.uiMode === 'moa') {
    return generateMOASignatoryTex(store);
  }

  // Properly capitalize names: First Middle LAST
  const firstName = capitalizeWord(data.sigFirst);
  const middleName = capitalizeWord(data.sigMiddle);
  const lastName = data.sigLast?.toUpperCase() || '';

  const fullName = [firstName, middleName, lastName]
    .filter(Boolean)
    .join(' ');

  // Abbreviated format: F. M. LASTNAME
  const abbrevName = [
    firstName ? `${firstName[0].toUpperCase()}.` : '',
    middleName ? `${middleName[0].toUpperCase()}.` : '',
    lastName,
  ]
    .filter(Boolean)
    .join(' ');

  let byDirectionTex = '';
  if (data.byDirection) {
    const authority = data.byDirectionAuthority || 'the Commanding Officer';
    byDirectionTex = `\\setByDirection{By direction of ${escapeLatex(authority)}}`;
  }

  // Set signature type and image
  // signatureType: 'none' = just typed name, 'image' = uploaded signature, 'digital' = empty field for CAC signing
  const signatureType = data.signatureType || 'none';
  let signatureConfigTex = '';

  if (signatureType === 'image' && data.signatureImage?.data) {
    // Use uploaded signature image
    signatureConfigTex = '\\setSignatureImage{signature.png}';
  } else if (signatureType === 'digital') {
    // Create empty digital signature field
    signatureConfigTex = '\\setDigitalSignatureField';
  } else {
    // No signature image or field
    signatureConfigTex = '\\setSignatureImage{}';
  }

  return `%=============================================================================
% SIGNATURE CONFIGURATION - Generated by libo-secured
%=============================================================================

\\setSignatory
    {${escapeLatex(firstName)}}
    {${escapeLatex(middleName)}}
    {${escapeLatex(lastName)}}
    {${escapeLatex(data.sigRank)}}
    {${escapeLatex(data.sigTitle)}}

\\setSignatoryName{${escapeLatex(fullName)}}
\\setSignatoryAbbrev{${escapeLatex(abbrevName)}}

${byDirectionTex}

${signatureConfigTex}
`;
}

// Generate MOA/MOU specific signatory configuration (dual signatures)
// Uses ONLY commands that exist in the original cached template
function generateMOASignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const signatureType = data.signatureType || 'none';

  // Digital signature field for dual signatures
  let signatureConfigTex = '';
  if (signatureType === 'digital') {
    signatureConfigTex = '\\setDigitalSignatureField';
  }

  // Senior signatory name formatting (same as standard signatory)
  const seniorFirstName = capitalizeWord(data.seniorSigName?.split(' ')[0]);
  const seniorLastName = data.seniorSigName?.split(' ').slice(-1)[0]?.toUpperCase() || '';
  const seniorFullName = data.seniorSigName || '';
  const seniorAbbrev = seniorFirstName ? `${seniorFirstName[0]}. ${seniorLastName}` : seniorLastName;

  // Use EXISTING commands only - Senior uses document-level fields + standard signatory
  // Junior uses Junior-prefixed fields (which already exist)
  return `%=============================================================================
% MOA/MOU DUAL SIGNATURE CONFIGURATION - Generated by libo-secured
%=============================================================================

% Senior Command (Signs Last - Right Side)
% Uses SeniorCommandName (exists) + document-level SSIC/Serial/Date + standard signatory
\\renewcommand{\\SeniorCommandName}{${escapeLatex(data.seniorCommandName)}}

% Senior signatory uses standard signatory fields
\\setSignatory
    {${escapeLatex(seniorFirstName)}}
    {}
    {${escapeLatex(seniorLastName)}}
    {${escapeLatex(data.seniorSigRank)}}
    {${escapeLatex(data.seniorSigTitle)}}
\\setSignatoryName{${escapeLatex(seniorFullName)}}
\\setSignatoryAbbrev{${escapeLatex(seniorAbbrev)}}

% Junior Command (Signs First - Left Side) - uses Junior-prefixed fields
\\renewcommand{\\JuniorCommandName}{${escapeLatex(data.juniorCommandName)}}
\\renewcommand{\\JuniorSSIC}{${escapeLatex(data.juniorSSIC)}}
\\renewcommand{\\JuniorSerial}{${escapeLatex(data.juniorSerial)}}
\\renewcommand{\\JuniorDate}{${escapeLatex(data.juniorDate)}}
\\renewcommand{\\JuniorSignatoryName}{${escapeLatex(data.juniorSigName)}}
\\renewcommand{\\JuniorSignatoryRank}{${escapeLatex(data.juniorSigRank)}}
\\renewcommand{\\JuniorSignatoryTitle}{${escapeLatex(data.juniorSigTitle)}}

${signatureConfigTex}
`;
}

export function generateFlagsTex(store: DocumentStore): string {
  let flags = '% Flags - Generated by libo-secured\n';
  if (store.references.length > 0) {
    flags += '\\setHasReferences\n';
  }
  if (store.enclosures.length > 0) {
    flags += '\\setHasEnclosures\n';
  }
  if (store.formData.includeHyperlinks) {
    flags += '\\setHyperlinksEnabled\n';
  }
  return flags;
}

export function generateReferencesTex(store: DocumentStore): string {
  if (store.references.length === 0) {
    return '% No references\n';
  }

  return `%=============================================================================
% REFERENCES - Generated by libo-secured
% Count: ${store.references.length} references
%=============================================================================

${store.references.map((r) => `\\refitem{${r.letter}}{${escapeLatex(r.title)}}`).join('\n')}
`;
}

export function generateReferenceUrlsTex(store: DocumentStore): string {
  const refsWithUrls = store.references.filter((r) => r.url?.trim());
  if (refsWithUrls.length === 0) return '% No reference URLs\n';

  return `%=============================================================================
% REFERENCE URLS - Generated by libo-secured
%=============================================================================

${refsWithUrls.map((r) => `\\setRefURL{${r.letter}}{${escapeLatexUrl(r.url)}}`).join('\n')}
`;
}

export function generateEnclosuresTex(store: DocumentStore): string {
  if (store.enclosures.length === 0) {
    return '% No enclosures\n';
  }

  return `%=============================================================================
% ENCLOSURES - Generated by libo-secured
% Count: ${store.enclosures.length} enclosures
%=============================================================================

${store.enclosures
    .map((e, i) => {
      // Always use JSPDF marker - JavaScript handles ALL enclosure pages
      // This ensures correct ordering (text-only and PDF enclosures in sequence)
      return `\\enclosure{${i + 1}}{JSPDF}{${escapeLatex(e.title || 'Untitled')}}`;
    })
    .join('\n')}
`;
}

export function generateCopyToTex(store: DocumentStore): string {
  if (store.copyTos.length === 0) {
    return '% No copy-to recipients\n';
  }

  return `%=============================================================================
% COPY TO (DISTRIBUTION) - Generated by libo-secured
% Count: ${store.copyTos.length} recipients
%=============================================================================

\\setHasCopyTo
${store.copyTos.map((ct, i) => `\\copytoentry{${i + 1}}{${escapeLatex(ct.text)}}`).join('\n')}
`;
}

export function generateBodyTex(store: DocumentStore): string {
  const labels = calculateLabels(store.paragraphs);

  let latex = `%=============================================================================
% DOCUMENT BODY - Generated by libo-secured
%=============================================================================

`;

  let openLevels: number[] = [];

  for (let i = 0; i < store.paragraphs.length; i++) {
    const para = store.paragraphs[i];
    const label = labels[i];

    // Close environments if level changes
    if (openLevels.length > 0 && openLevels[openLevels.length - 1] !== para.level) {
      const closingLevel = openLevels.pop()!;
      latex += getCloseEnvironment(closingLevel) + '\n\n';
    }

    if (para.level === 0) {
      latex += `\\vspace{12pt}\n\\noindent ${label}  ${processBodyText(para.text)}\n\n`;
    } else {
      if (openLevels.length === 0) {
        latex += getOpenEnvironment(para.level) + '\n';
        openLevels.push(para.level);
      }
      latex += `\\item ${processBodyText(para.text)}\n\n`;
    }
  }

  // Close remaining environments
  while (openLevels.length > 0) {
    const closingLevel = openLevels.pop()!;
    latex += getCloseEnvironment(closingLevel) + '\n';
  }

  return latex;
}

function getOpenEnvironment(level: number): string {
  switch (level) {
    case 1: return '\\begin{subpara}';
    case 2: return '\\begin{subsubpara}';
    case 3: return '\\begin{subsubsubpara}';
    case 4: return '\\begin{subsubsubsubpara}';
    case 5: return '\\begin{subsubsubsubsubpara}';
    case 6: return '\\begin{subsubsubsubsubsubpara}';
    case 7: return '\\begin{subsubsubsubsubsubsubpara}';
    default: return '\\begin{subpara}';
  }
}

function getCloseEnvironment(level: number): string {
  switch (level) {
    case 1: return '\\end{subpara}';
    case 2: return '\\end{subsubpara}';
    case 3: return '\\end{subsubsubpara}';
    case 4: return '\\end{subsubsubsubpara}';
    case 5: return '\\end{subsubsubsubsubpara}';
    case 6: return '\\end{subsubsubsubsubsubpara}';
    case 7: return '\\end{subsubsubsubsubsubsubpara}';
    default: return '\\end{subpara}';
  }
}

export function generateClassificationTex(store: DocumentStore): string {
  const data = store.formData;

  if (data.classLevel === 'unclassified' || !data.classLevel) {
    return '% Unclassified - no classification markings\n';
  }

  if (data.classLevel === 'cui') {
    return `%=============================================================================
% CUI CONFIGURATION - Generated by libo-secured
%=============================================================================

\\setCUI
\\setCUIControlledBy{${escapeLatex(data.cuiControlledBy)}}
\\setCUICategory{${escapeLatex(data.cuiCategory)}}
\\setCUIDissemination{${escapeLatex(data.cuiDissemination)}}
\\setCUIDistStatement{${escapeLatex(data.cuiDistStatement)}}
\\setPOC{${escapeLatex(data.pocEmail)}}
`;
  }

  const classLevelMap: Record<string, string> = {
    confidential: 'CONFIDENTIAL',
    secret: 'SECRET',
    top_secret: 'TOP SECRET',
    top_secret_sci: 'TOP SECRET//SCI',
  };

  return `%=============================================================================
% CLASSIFICATION CONFIGURATION - Generated by libo-secured
%=============================================================================

\\setClassification{${classLevelMap[data.classLevel] || 'SECRET'}}
\\setClassifiedBy{${escapeLatex(data.classifiedBy)}}
\\setDerivedFrom{${escapeLatex(data.derivedFrom)}}
\\setDeclassifyOn{${escapeLatex(data.declassifyOn)}}
\\setClassificationReason{${escapeLatex(data.classReason)}}
\\setPOC{${escapeLatex(data.classifiedPocEmail)}}
`;
}

export interface EnclosureData {
  number: number;
  title: string;
  data?: ArrayBuffer; // undefined = text-only enclosure (no PDF)
  pageStyle?: 'border' | 'fullpage' | 'fit';
  hasCoverPage?: boolean;
  coverPageDescription?: string;
}

export interface GeneratedFiles {
  texFiles: Record<string, string>;
  enclosures: EnclosureData[];
  includeHyperlinks: boolean;
  signatureImage?: Uint8Array; // PNG data for signature image
}

// Helper to convert base64 to Uint8Array
function base64ToUint8Array(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

export function generateAllLatexFiles(store: DocumentStore): GeneratedFiles {
  // Files are written to root level to match \input{} paths in latex-templates.js
  const texFiles: Record<string, string> = {
    'document.tex': generateDocumentTex(store),
    'letterhead.tex': generateLetterheadTex(store),
    'signatory.tex': generateSignatoryTex(store),
    'flags.tex': generateFlagsTex(store),
    'references.tex': generateReferencesTex(store),
    'reference-urls.tex': generateReferenceUrlsTex(store),
    'encl-config.tex': generateEnclosuresTex(store),
    'copyto-config.tex': generateCopyToTex(store),
    'body.tex': generateBodyTex(store),
    'classification.tex': generateClassificationTex(store),
  };

  // Collect ALL enclosures for JavaScript handling (maintains correct order)
  const enclosures: EnclosureData[] = store.enclosures.map((encl, i) => ({
    number: i + 1,
    title: encl.title || 'Untitled',
    data: encl.file?.data, // undefined if no PDF attached
    pageStyle: encl.pageStyle,
    hasCoverPage: encl.hasCoverPage,
    coverPageDescription: encl.coverPageDescription,
  }));

  // Convert signature image from base64 to Uint8Array if present
  const signatureImage = store.formData.signatureImage?.data
    ? base64ToUint8Array(store.formData.signatureImage.data)
    : undefined;

  return { texFiles, enclosures, includeHyperlinks: !!store.formData.includeHyperlinks, signatureImage };
}
